<a href="https://colab.research.google.com/github/Kazi-Irfanul-Islam/ML-DL-related-codes/blob/main/NumPy_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<Center>

**`NumPy Tutorials in Python For Machine Learning`**
</Center>


Documentation Link: [NumPy User Guide](https://numpy.org/devdocs/user/index.html#user)

***NumPy - Numerical Python***

---

Advantages OF NumPy Arrays:


> Allows several Mathematical Operations

> Faster Operations





In [2]:
import numpy as np

**List vs NumPy - Time Taken**

In [2]:
from time import process_time

Time taken By a **`LIST`**

In [4]:
python_list = [i for i in range(1000000)]

start_time = process_time()

python_list = [i + 5 for i in range(1000000)]

end_time = process_time()

print(end_time - start_time);

0.06722801


Time Taken by - **`NumPy Array`**


In [6]:
np_array = np.array([i for i in range(1000000)]);

start_time = process_time()

np_array += 5;

end_time = process_time()

print(end_time - start_time)

0.0008997310000005143


So NumPy Array are `5 - 10% `faster to execute

<Center>NumPy Arrays</Center>

In [12]:
#List
list1 = [10, 20, 30, 40, 50]
print(list1)
type(list1)


#NumPy Array

np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[10, 20, 30, 40, 50]
[1 2 3 4 5]


numpy.ndarray

Creating 1 Dimentional Array

In [17]:
a = np.array([1, 2, 3, 4, 5]);
print(a)
a.shape

[1 2 3 4 5]


(5,)

Creating 2-dimensional Array

In [20]:
b = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

Initial PlaceHolder's in NumPy Arrays

In [25]:
# create a numpy array of zeros/ones
x = np.ones((4, 4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
# Create a numPy Array of a Particular Value/
xx = np.full((4, 4), 69)
print(xx)

[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]


In [29]:
# Create An identity Matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
# create a numPy array with random values
aa = np.random.rand(4, 4)
print(aa)

[[0.7989125  0.18435756 0.89698664 0.03418781]
 [0.67983157 0.60867651 0.57471564 0.61339069]
 [0.87817455 0.15488776 0.7946418  0.84327571]
 [0.00607422 0.70070577 0.75593947 0.89550016]]


In [38]:
# random integer value array within a speicific range
c = np.random.randint(10, 100, (3, 5)) # (begin, end, (rows, cols))
print(c)

[[67 70 14 10 30]
 [74 46 32 13 41]
 [63 30 98 75 32]]


In [11]:
# array of evenly spaced values => specifying the number of values required
d = np.linspace(10, 30, 4)
print(d)

[10.         16.66666667 23.33333333 30.        ]


In [6]:
# array of evenly spaced values => specifying the Steps
e = np.arange(10, 50, 5)
print(e)

[10 15 20 25 30 35 40 45]


In [7]:
# Convert a list into NumPy Array
list2 = [10, 20, 20, 50]
np_arr = np.asarray(list2)
print(np_arr)
type(np_arr)

[10 20 20 50]


numpy.ndarray

In [8]:
# Analyzing a NumPy Array
c = np.random.randint(10, 30, (4, 4))
print(c)

[[20 16 11 27]
 [29 29 23 27]
 [14 26 20 22]
 [21 19 17 10]]


In [9]:
# array dimension
print(c.shape)

(4, 4)


In [10]:
# Number of Dimension
print(c.ndim)

2


In [11]:
# Number of Elements in an Array
print(c.size)

16


In [12]:
# Checking the dataTypes of values in an array
print(c.dtype)

int64


<Center>

**`Mathematical Operations on a NumPy Array`**
 </Center>

In [13]:
list1 = [1, 2, 3, 4, 5]
list2 = [5, 6, 7, 8, 9]
print(list1 + list2)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [15]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 1 0]
 [4 5 3]
 [0 8 0]]
[[11 12 12]
 [14 15 13]
 [11 14 10]]


In [16]:
print(a + b)
print(a - b)
print(a / b)
print(a * b)

[[15 13 12]
 [18 20 16]
 [11 22 10]]
[[ -7 -11 -12]
 [-10 -10 -10]
 [-11  -6 -10]]
[[0.36363636 0.08333333 0.        ]
 [0.28571429 0.33333333 0.23076923]
 [0.         0.57142857 0.        ]]
[[ 44  12   0]
 [ 56  75  39]
 [  0 112   0]]


In [18]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 9 5]
 [0 6 4]
 [6 0 4]]
[[13 11 12]
 [11 14 14]
 [19 19 17]]


In [19]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[20 20 17]
 [11 20 18]
 [25 19 21]]
[[ -6  -2  -7]
 [-11  -8 -10]
 [-13 -19 -13]]
[[ 91  99  60]
 [  0  84  56]
 [114   0  68]]
[[0.53846154 0.81818182 0.41666667]
 [0.         0.42857143 0.28571429]
 [0.31578947 0.         0.23529412]]


<Center>

**` Numpy Array Manipulation`**
 </Center>

In [20]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)


[[0 3 5]
 [0 5 3]]
(2, 3)


In [21]:
#Transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 0]
 [3 5]
 [5 3]]
(3, 2)


In [22]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 4 5]
 [8 8 3]]
(2, 3)


In [23]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 8]
 [4 8]
 [5 3]]
(3, 2)


In [24]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 0 8]
 [7 7 8]]
(2, 3)


In [27]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 0]
 [8 7]
 [7 8]]
(3, 2)
