<Center>NumPy Tutorials in Python For Machine Learning</Center>


Documentation Link: [NumPy User Guide](https://numpy.org/devdocs/user/index.html#user)

***NumPy - Numerical Python***

---

Advantages OF NumPy Arrays:


> Allows several Mathematical Operations

> Faster Operations





In [1]:
import numpy as np

**List vs NumPy - Time Taken**

In [2]:
from time import process_time

Time taken By a **`LIST`**

In [4]:
python_list = [i for i in range(1000000)]

start_time = process_time()

python_list = [i + 5 for i in range(1000000)]

end_time = process_time()

print(end_time - start_time);

0.06722801


Time Taken by - **`NumPy Array`**


In [6]:
np_array = np.array([i for i in range(1000000)]);

start_time = process_time()

np_array += 5;

end_time = process_time()

print(end_time - start_time)

0.0008997310000005143


So NumPy Array are `5 - 10% `faster to execute

<Center>NumPy Arrays</Center>

In [12]:
#List
list1 = [10, 20, 30, 40, 50]
print(list1)
type(list1)


#NumPy Array

np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[10, 20, 30, 40, 50]
[1 2 3 4 5]


numpy.ndarray

Creating 1 Dimentional Array

In [17]:
a = np.array([1, 2, 3, 4, 5]);
print(a)
a.shape

[1 2 3 4 5]


(5,)

Creating 2-dimensional Array

In [20]:
b = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

Initial PlaceHolder's in NumPy Arrays

In [25]:
# create a numpy array of zeros
x = np.ones((4, 4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
